---
- name: Create group {{ group_name }}
  group:
    name: "{{ group_name }}"
    system: true
    state: present

- name: Create user {{ user_name }}
  user:
    name: "{{ user_name }}"
    group: "{{ group_name }}"
    append: yes
    groups: "sudo"
    system: true
    create_home: true
    home: /home/{{ user_name }}
    shell: /bin/bash
    password: "{{ 'example' | password_hash('sha512') }}"
